version: '3'
services:
  react-js:
    build:
      context: ./React_Js
      dockerfile: "Dockerfile.Reactjs"
    ports:
      - "3000:3000"
    restart: "unless-stopped"
    depends_on:
      - "node-js"
    environment:
      BASEURL: http://localhost:3000
  node-js:
    build:
      context: ./Node_Js
      dockerfile: "Dockerfile.Nodejs"
    ports:
      - "3001:3001"
    depends_on:
      - "mongodb-server"
    restart: "always"
    volumes:
      - /usr/resume_parser/Node_Js/node_modules
      - ./Node_Js:/usr/resume_parser/Node_Js
    environment:
      PORTNO: 3001
      DATABASE_URL: mongodb://docker:mongopw@mongodb-server:27017
      BASE_URL: http://node-js:3001
  mongodb-server:
    image: "mongo"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_PASSWORD: mongopw
      MONGO_INITDB_ROOT_USERNAME: docker
    ports:
      - "27017:27017"
