version: '3'
services:
  nginix:
    build:
      context: ./Nginx
      dockerfile: "Dockerfile.Nginx"
    restart: always
    ports:
      - "8080:80"
  react-js:
    build:
      context: ./React_Js
      dockerfile: "Dockerfile.Reactjs"
    restart: "unless-stopped"
    depends_on:
      - "node-js"
  node-js:
    build:
      context: ./Node_Js
      dockerfile: "Dockerfile.Nodejs"
    depends_on:
      - "mongodb-server"
    restart: "always"
    volumes:
      - /usr/resume_parser/Node_Js/node_modules
      - ./Node_Js:/usr/resume_parser/Node_Js
    environment:
      PORTNO: 3001
      DATABASE_URL: mongodb://docker:mongopw@mongodb-server:27017
      BASE_URL: /api
  mongodb-server:
    image: "mongo"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_PASSWORD: mongopw
      MONGO_INITDB_ROOT_USERNAME: docker
